apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: busybox
      command:
        - sleep
        - "3600"
  restartPolicy: Always
