apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler
  namespace: dist-sched
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: dist-sched
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-admin-user
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: dist-sched
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-scheduler-monitor
  namespace: dist-sched
  labels:
    k8s-app: my-scheduler
    release: kube-prometheus-stack-1688584345
spec:
  selector:
    matchLabels:
      app: my-scheduler-app
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: my-scheduler-svc
  namespace: dist-sched
  labels:
    app: my-scheduler-app
spec:
  selector:
    component: scheduler
    tier: control-plane
    name: my-scheduler
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 8080
---