apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-home1
  namespace: logging
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  hostPath:
    path: "/mnt/data/es1"
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-home2
  namespace: logging
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  hostPath:
    path: "/mnt/data/es2"
  accessModes:
    - ReadWriteOnce
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: es-pv-home3
      namespace: logging
      labels:
        type: local
    spec:
      capacity:
        storage: 4Gi
      hostPath:
        path: "/mnt/data/es3"
      accessModes:
        - ReadWriteOnce


kind: List
